blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^category/$', views.CategoryView.as_view(), name='category'),
	url(r'^aboutme/$', views.aboutme, name='aboutme'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

blog/models.py
import datetime
from django.db import models
from django.utils import timezone


class Tag(models.Model):
	name = models.CharField(max_length=20)

	def __str__(self):
		return self.name

    
class Article(models.Model):
    title = models.CharField(max_length=40)
    content = models.TextField()
    pub_date = models.DateTimeField('date published') # auto_now_add=True
    tags = models.ManyToManyField(Tag, blank=True)
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1     #更新浏览的次数，还未保存到数据库
        self.save(update_fields = ['views'])    #用save方法保存到数据库, update_fields 参数来告诉 Django 只更新数据库中 views 字段的值，以提高效率。  

    def __str__(self):
        return self.title
    
    def intro(self):
        return self.content[:self.content.find('\n')]

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator


from .models import Article, Tag

class IndexView(generic.ListView):
    template_name = 'blog/base_index.html'
    context_object_name = 'articles'
    paginate_by = 4
    def get_queryset(self):
        return Article.objects.all().order_by('-pub_date')

class DetailView(generic.DetailView):
    model = Article
    template_name = 'blog/base_detail.html'
    context_object_name = 'article'

    def get_queryset(self):
        return Article.objects.all()

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(DetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()
        # 视图必须返回一个 HttpResponse 对象
        return response

class CategoryView(generic.ListView):
    model = Tag
    template_name = 'blog/base_category.html'
    context_object_name = 'tags'
    def get_queryset(self):
        return Tag.objects.all()


def aboutme(request):
    return render(request, 'blog/base_aboutme.html')

blog/templates/blog/base.html
{% load static %}<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>UNIVERSR</title>
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'blog/images/favicon.ico' %}" media="screen" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
  <link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css">
</head>
<body> 
<div class="container">
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded" id="index-top-color">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand " href="#">Simon</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    {% block navbarSupportedContent %}
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'blog:index' %}"> <span class="fa fa-home"></span> Home <span class="sr-only">(current)</span></a>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:aboutme' %}">About Me</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link " href="{% url 'blog:category' %}"><span class="fa fa-archive"></span> Category</a>
        </li>
      </ul>
      {% endblock %}

      <div class="form-inline my-2 my-lg-0">
        <ul class="ul-img">
          <li class="li-img">
            <a href="https://github.com/SimonZoo" target="_blank" ><img src="/static/blog/images/github.png" class="little-img" id="github-logo"></a>
          </li>
        </ul>
      </div>

    </div>
  </nav>
</div>

<div class="container-fluid">
  <div class="row"> 
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div id="blog-content" >
        {% block blog-content %}{% endblock %}
      </div>
    </div>

  </div>
</div>
<script type="text/javascript">
  window.onload = function () {

    var githubLogo = document.getElementById("github-logo");
    githubLogo.onmouseover = function() {
      githubLogo.src = "/static/blog/images/github-hover.png";
    }
    githubLogo.onmouseout = function() {
      githubLogo.src = "/static/blog/images/github.png";
    }
  }
</script>

<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/base_aboutme.html
{% extends "blog/base.html" %}
{% block blog-content %}
<div class="container ">
  <div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-10" id="aboutme">
        <h3><img src="/static/blog/images/astronaut.png" alt="astronaut" class="little-img">About Me</h3>
        <hr>
        <p>Junior Student / University</p>
        <p>有一颗想成为全栈的心的未来前端。</p>
        <p>Python / JavaScript / Bootstrap 学习中</p>
        <p><del>嗯...?!不对，我是要征服宇宙的宇航员。</del></p><br>
  
        <h3>Main Works</h3>
        <hr>
        <p>你所看到的这个用Django搭建的网站，还有一个简陋的贪吃蛇。</p>
        <p>挺上去好像太少或者没什么技术含量？没关系，我还在学习。</p><br>
      </div>
      
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/base_category.html
{% extends "blog/base.html" %}

{% block blog-content %}

<div class="container-fluid">
    <div class="row"> 
        <div class="col-md-8">
            <div class="list-group">
                {% for article in articles %}
                <a href="#" class="list-group-item list-group-item-action flex-column  align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ article.title|title }}</h5>
                        <small class="text-muted">{{ article.pub_date | date:"M  d  Y" }}</small>
                    </div>
                    <p class="mb-1">{{ article.intro }}</p>
                    <small class="text-muted">Read More</small>
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4">
            <ul class="list-group">
                {% for tag in tags %}
                <li class="list-group-item justify-content-between">
                    <a href="#">{{ tag }}</a>
                <span class="badge badge-default badge-pill">14</span>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/base_detail.html
{% extends "blog/base.html" %}
{% block blog-content %}{% load markdown2html %}
<div class="panel-top">
  <div class="card ">  
    <div class="card-block">
      <div class="text-center ">
        <h2 class="card-title light-title">{{ article }}</h2>
        <hr>
        <h6 class="card-title light-title">{{ article.pub_date }} | <img src="/static/blog/images/views.png"> {{ article.views }} </h6>
      </div class="card-text">
        {{ article.content|markdown2html }}
      </div>
    <div class="card-footer text-muted text-center">Edited Before {{ article.pub_date|timesince }}
    </div> 
  </div>
</div>

{% endblock %}

blog/templates/blog/base_index.html
{% extends "blog/base.html" %}

{% block blog-content %}
{% for article in articles %}
      <div class="card panel-top">
      <h6 class="card-header light-title">{{ article.pub_date | date:"M  d  Y" }}</h6>
        <div class="card-block">
          <h4 class="card-title light-title">{{ article.title|title }} 
          {% for tag in article.tags.all %}
            <span class="badge badge-default light-title " id="article-tag">{{ tag }}</span>
          {% endfor %}
          </h4>
          <p class="card-text">{{ article.intro }}</p>
          <a href="{% url 'blog:detail' article.id %}" class="btn btn-outline-info">Click Here</a>
        </div>
      </div>
{% endfor %}
   
<div class="pagination-simple">
  <nav aria-label="page navigation">
    <ul class="pagination justify-content-center nav-bottom">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      {% else %}
          <a class="page-link page-item" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
      {% endif %}

      <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li> 
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
        </a>
        {% else %}
        <a class="page-link page-item" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
        </a>
        {% endif %}
    </ul>
  </nav>
</div>

{% endblock %}